// <auto-generated />
using System;
using ControlDeGastosNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlDeGastosNetCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528193613_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlDeGastosNetCore.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Categorias");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ControlDeGastosNetCore.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Gastos");

                    b.HasIndex(new[] { "CategoriaId" }, "IX_CategoriaId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("ControlDeGastosNetCore.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Año")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Presupuestos");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("ControlDeGastosNetCore.Models.Gasto", b =>
                {
                    b.HasOne("ControlDeGastosNetCore.Models.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Gastos_dbo.Categorias_CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControlDeGastosNetCore.Models.Categoria", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
